import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  client: {
    NEXT_PUBLIC_BASE_TITLE: z.coerce.string(),
    NEXT_PUBLIC_BASE_URL: z.coerce.string(),
    NEXT_PUBLIC_KLAVIYO_API_KEY: z.coerce.string(),
  },
  emptyStringAsUndefined: true,
  runtimeEnv: {
    CLOUDFRONT_DISTRIBUTION: process.env.CLOUDFRONT_DISTRIBUTION,
    DATABASE_URI: process.env.DATABASE_URI,
    KLAVIYO_API_KEY: process.env.KLAVIYO_API_KEY,
    MUX_ACCESS_TOKEN_ID: process.env.MUX_ACCESS_TOKEN_ID,
    MUX_JWT_PRIVATE_KEY: process.env.MUX_JWT_PRIVATE_KEY,
    MUX_JWT_SIGNING_KEY: process.env.MUX_JWT_SIGNING_KEY,
    MUX_SECRET_KEY: process.env.MUX_SECRET_KEY,
    MUX_WEBHOOK_SECRET: process.env.MUX_WEBHOOK_SECRET,
    NEXT_PUBLIC_BASE_TITLE: process.env.NEXT_PUBLIC_BASE_TITLE,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_KLAVIYO_API_KEY: process.env.NEXT_PUBLIC_KLAVIYO_API_KEY,
    NODE_ENV: process.env.NODE_ENV,
    PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
    S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
    S3_BUCKET: process.env.S3_BUCKET,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_REGION: process.env.S3_REGION,
    S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
    VERCEL_URL: process.env.VERCEL_URL,
  },
  server: {
    CLOUDFRONT_DISTRIBUTION: z.string(),
    DATABASE_URI: z.string(),
    KLAVIYO_API_KEY: z.coerce.string(),
    MUX_ACCESS_TOKEN_ID: z.string(),
    MUX_JWT_PRIVATE_KEY: z.string(),
    MUX_JWT_SIGNING_KEY: z.string(),
    MUX_SECRET_KEY: z.string(),
    MUX_WEBHOOK_SECRET: z.string(),
    NODE_ENV: z.enum(["development", "testing", "staging", "production"]).default("development"),
    PAYLOAD_SECRET: z.string(),
    S3_ACCESS_KEY_ID: z.string(),
    S3_BUCKET: z.string(),
    S3_ENDPOINT: z.string(),
    S3_REGION: z.string(),
    S3_SECRET_ACCESS_KEY: z.string(),
    VERCEL_URL: z.string().default("http://localhost:4000"),
  },
});
